# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"V\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12order_payload_json\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x03(\x05\")\n\x11InitOrderResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"/\n\x0e\x42ookSuggestion\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\":\n\x11OrderEventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0bincoming_vc\x18\x02 \x03(\x05\"q\n\x12OrderEventResponse\x12\x0c\n\x04\x66\x61il\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02vc\x18\x03 \x03(\x05\x12\x30\n\x0bsuggestions\x18\x04 \x03(\x0b\x32\x1b.suggestions.BookSuggestion\"C\n\x13\x43leanupOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12\x66inal_vector_clock\x18\x02 \x03(\x05\"f\n\x14\x43leanupOrderResponse\x12\x0f\n\x07\x63leaned\x18\x01 \x01(\x08\x12\x10\n\x08vc_valid\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x1a\n\x12local_vector_clock\x18\x04 \x03(\x05\x32\x8d\x02\n\x12SuggestionsService\x12J\n\tInitOrder\x12\x1d.suggestions.InitOrderRequest\x1a\x1e.suggestions.InitOrderResponse\x12V\n\x13GenerateSuggestions\x12\x1e.suggestions.OrderEventRequest\x1a\x1f.suggestions.OrderEventResponse\x12S\n\x0c\x43leanupOrder\x12 .suggestions.CleanupOrderRequest\x1a!.suggestions.CleanupOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITORDERREQUEST']._serialized_start=34
  _globals['_INITORDERREQUEST']._serialized_end=120
  _globals['_INITORDERRESPONSE']._serialized_start=122
  _globals['_INITORDERRESPONSE']._serialized_end=163
  _globals['_BOOKSUGGESTION']._serialized_start=165
  _globals['_BOOKSUGGESTION']._serialized_end=212
  _globals['_ORDEREVENTREQUEST']._serialized_start=214
  _globals['_ORDEREVENTREQUEST']._serialized_end=272
  _globals['_ORDEREVENTRESPONSE']._serialized_start=274
  _globals['_ORDEREVENTRESPONSE']._serialized_end=387
  _globals['_CLEANUPORDERREQUEST']._serialized_start=389
  _globals['_CLEANUPORDERREQUEST']._serialized_end=456
  _globals['_CLEANUPORDERRESPONSE']._serialized_start=458
  _globals['_CLEANUPORDERRESPONSE']._serialized_end=560
  _globals['_SUGGESTIONSSERVICE']._serialized_start=563
  _globals['_SUGGESTIONSSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
