# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/books_database/booksdatabase.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/books_database/booksdatabase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+utils/pb/books_database/booksdatabase.proto\x12\rbooksdatabase\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x94\x01\n\rBooksDatabase\x12?\n\x04Read\x12\x1a.booksdatabase.ReadRequest\x1a\x1b.booksdatabase.ReadResponse\x12\x42\n\x05Write\x12\x1b.booksdatabase.WriteRequest\x1a\x1c.booksdatabase.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.books_database.booksdatabase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=62
  _globals['_READREQUEST']._serialized_end=90
  _globals['_READRESPONSE']._serialized_start=92
  _globals['_READRESPONSE']._serialized_end=121
  _globals['_WRITEREQUEST']._serialized_start=123
  _globals['_WRITEREQUEST']._serialized_end=171
  _globals['_WRITERESPONSE']._serialized_start=173
  _globals['_WRITERESPONSE']._serialized_end=205
  _globals['_BOOKSDATABASE']._serialized_start=208
  _globals['_BOOKSDATABASE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
