# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/books_database/booksdatabase.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'utils/pb/books_database/booksdatabase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+utils/pb/books_database/booksdatabase.proto\x12\rbooksdatabase\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\x0bStockUpdate\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\"O\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12+\n\x07updates\x18\x02 \x03(\x0b\x32\x1a.booksdatabase.StockUpdate\"1\n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"2\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xe9\x02\n\rBooksDatabase\x12?\n\x04Read\x12\x1a.booksdatabase.ReadRequest\x1a\x1b.booksdatabase.ReadResponse\x12\x42\n\x05Write\x12\x1b.booksdatabase.WriteRequest\x1a\x1c.booksdatabase.WriteResponse\x12H\n\x07Prepare\x12\x1d.booksdatabase.PrepareRequest\x1a\x1e.booksdatabase.PrepareResponse\x12\x45\n\x06\x43ommit\x12\x1c.booksdatabase.CommitRequest\x1a\x1d.booksdatabase.CommitResponse\x12\x42\n\x05\x41\x62ort\x12\x1b.booksdatabase.AbortRequest\x1a\x1c.booksdatabase.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.books_database.booksdatabase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=62
  _globals['_READREQUEST']._serialized_end=90
  _globals['_READRESPONSE']._serialized_start=92
  _globals['_READRESPONSE']._serialized_end=121
  _globals['_WRITEREQUEST']._serialized_start=123
  _globals['_WRITEREQUEST']._serialized_end=171
  _globals['_WRITERESPONSE']._serialized_start=173
  _globals['_WRITERESPONSE']._serialized_end=205
  _globals['_STOCKUPDATE']._serialized_start=207
  _globals['_STOCKUPDATE']._serialized_end=254
  _globals['_PREPAREREQUEST']._serialized_start=256
  _globals['_PREPAREREQUEST']._serialized_end=335
  _globals['_PREPARERESPONSE']._serialized_start=337
  _globals['_PREPARERESPONSE']._serialized_end=386
  _globals['_COMMITREQUEST']._serialized_start=388
  _globals['_COMMITREQUEST']._serialized_end=421
  _globals['_COMMITRESPONSE']._serialized_start=423
  _globals['_COMMITRESPONSE']._serialized_end=473
  _globals['_ABORTREQUEST']._serialized_start=475
  _globals['_ABORTREQUEST']._serialized_end=507
  _globals['_ABORTRESPONSE']._serialized_start=509
  _globals['_ABORTRESPONSE']._serialized_end=541
  _globals['_BOOKSDATABASE']._serialized_start=544
  _globals['_BOOKSDATABASE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
