# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\"V\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12order_payload_json\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x03(\x05\")\n\x11InitOrderResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\":\n\x11OrderEventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0bincoming_vc\x18\x02 \x03(\x05\"q\n\x12OrderEventResponse\x12\x0c\n\x04\x66\x61il\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02vc\x18\x03 \x03(\x05\x12\x30\n\x0bsuggestions\x18\x04 \x03(\x0b\x32\x1b.transaction.BookSuggestion\"/\n\x0e\x42ookSuggestion\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"C\n\x13\x43leanupOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12\x66inal_vector_clock\x18\x02 \x03(\x05\"f\n\x14\x43leanupOrderResponse\x12\x0f\n\x07\x63leaned\x18\x01 \x01(\x08\x12\x10\n\x08vc_valid\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x1a\n\x12local_vector_clock\x18\x04 \x03(\x05\x32\xb9\x03\n\x1eTransactionVerificationService\x12J\n\tInitOrder\x12\x1d.transaction.InitOrderRequest\x1a\x1e.transaction.InitOrderResponse\x12N\n\x0bVerifyItems\x12\x1e.transaction.OrderEventRequest\x1a\x1f.transaction.OrderEventResponse\x12Q\n\x0eVerifyUserData\x12\x1e.transaction.OrderEventRequest\x1a\x1f.transaction.OrderEventResponse\x12S\n\x10VerifyCardFormat\x12\x1e.transaction.OrderEventRequest\x1a\x1f.transaction.OrderEventResponse\x12S\n\x0c\x43leanupOrder\x12 .transaction.CleanupOrderRequest\x1a!.transaction.CleanupOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITORDERREQUEST']._serialized_start=47
  _globals['_INITORDERREQUEST']._serialized_end=133
  _globals['_INITORDERRESPONSE']._serialized_start=135
  _globals['_INITORDERRESPONSE']._serialized_end=176
  _globals['_ORDEREVENTREQUEST']._serialized_start=178
  _globals['_ORDEREVENTREQUEST']._serialized_end=236
  _globals['_ORDEREVENTRESPONSE']._serialized_start=238
  _globals['_ORDEREVENTRESPONSE']._serialized_end=351
  _globals['_BOOKSUGGESTION']._serialized_start=353
  _globals['_BOOKSUGGESTION']._serialized_end=400
  _globals['_CLEANUPORDERREQUEST']._serialized_start=402
  _globals['_CLEANUPORDERREQUEST']._serialized_end=469
  _globals['_CLEANUPORDERRESPONSE']._serialized_start=471
  _globals['_CLEANUPORDERRESPONSE']._serialized_end=573
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=576
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
