# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\"\x12\n\x10GetStatusRequest\"h\n\x11GetStatusResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x11\n\tis_leader\x18\x02 \x01(\x08\x12\x11\n\tleader_id\x18\x03 \x01(\t\x12\x18\n\x10processed_orders\x18\x04 \x01(\x03\x32\\\n\x14OrderExecutorService\x12\x44\n\tGetStatus\x12\x1a.executor.GetStatusRequest\x1a\x1b.executor.GetStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATUSREQUEST']._serialized_start=28
  _globals['_GETSTATUSREQUEST']._serialized_end=46
  _globals['_GETSTATUSRESPONSE']._serialized_start=48
  _globals['_GETSTATUSRESPONSE']._serialized_end=152
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=154
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
